'use client';

import type { SentimentAnalysis, SentimentType } from '@/types/movie';

interface SentimentCardProps {
  sentiment: SentimentAnalysis;
}

const sentimentConfig: Record<SentimentType, { color: string; bgColor: string; icon: string }> = {
  Positive: {
    color: 'text-positive',
    bgColor: 'bg-green-50 border-green-200',
    icon: '😊',
  },
  Mixed: {
    color: 'text-mixed',
    bgColor: 'bg-yellow-50 border-yellow-200',
    icon: '😐',
  },
  Negative: {
    color: 'text-negative',
    bgColor: 'bg-red-50 border-red-200',
    icon: '😞',
  },
};

export default function SentimentCard({ sentiment }: SentimentCardProps) {
  const config = sentimentConfig[sentiment.classification];

  return (
    <div
      className={`rounded-lg sm:rounded-xl border-2 p-4 sm:p-6 ${config.bgColor} animate-fade-in`}
    >
      <div className="flex flex-col sm:flex-row items-start gap-3 sm:gap-4">
        {/* Icon */}
        <div className="text-3xl sm:text-4xl flex-shrink-0">{config.icon}</div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3 mb-3">
            <h3 className="text-base sm:text-lg lg:text-xl font-bold text-gray-900">
              AI Audience Sentiment
            </h3>
            <span
              className={`px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-semibold ${config.color} bg-white inline-block w-fit`}
            >
              {sentiment.classification}
            </span>
          </div>

          <p className="text-sm sm:text-base text-gray-800 leading-relaxed">{sentiment.summary}</p>

          <div className="mt-3 sm:mt-4 text-xs text-gray-500 italic">
            Generated by AI • Based on audience reviews
          </div>
        </div>
      </div>
    </div>
  );
}
